# Generated by Django 4.1.7 on 2023-04-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secret_id', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=100)),
                ('condition', models.CharField(max_length=100)),
            ],
        ),
    ]
